//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRedirect.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>vMi13IPasnYfvPC+S1rXF0HoTkA=</string>
  <string>Q/LO36T/x8Ce/gy09HX9D+Qkrqg=</string>
  <string>dUvDe923foCr7xl7SgSpFC7lLVY=</string>
  <string>eVAaW2DkZC8qhLLM2io3xP4NjxM=</string>
  <string>8srLXv9vEsHkkSiz2+aT75s/CoA=</string>
  <string>Ou7uQHY7khdrAiOwwMcDmwTW2nU=</string>
  <string>e3dvocUFTE1UWIvtW8qzulnWErI=</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection uids {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["uids"]));
            }
            set {
                this["uids"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enabled {
            get {
                return ((bool)(this["enabled"]));
            }
            set {
                this["enabled"] = value;
            }
        }
    }
}
